Unkcon/Controllers/CommentController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Unkcon.Authentication;
using Unkcon.DAL;
using Unkcon.Models;

namespace Unkcon.Controllers
{
    public class CommentController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        private UserManagerDecorator _userManager;

        public CommentController()
        {
            _userManager = new UserManagerDecorator(_db);
        }

        // Broser other people's comments
        public async Task<ActionResult> Browse()
        {
            ApplicationUser currentUser = await _userManager.GetCurrentUserAsync(User.Identity.GetUserId());

            if (currentUser == null)
            {
                return View();
            }
            else
            {
                return View(_db.Comments.ToList().Where(c => c.User != currentUser));
            }

        }

        // See own comments
        public async Task<ActionResult> Index()
        {
            ApplicationUser currentUser = await _userManager.GetCurrentUserAsync(User.Identity.GetUserId());

            if (currentUser == null)
            {
                return View();
            }
            else
            {
                return View(_db.Comments.ToList().Where(c => c.User == currentUser));
            }
        }

        // GET: /Comment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentModel commentmodel = _db.Comments.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        // GET: /Comment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Comment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="ID,Comment")] CommentModel commentmodel)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetCurrentUserAsync(User.Identity.GetUserId());

                commentmodel.User = currentUser;
                _db.Comments.Add(commentmodel);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(commentmodel);
        }

        // GET: /Comment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentModel commentmodel = _db.Comments.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        // POST: /Comment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Comment")] CommentModel commentmodel)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(commentmodel).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(commentmodel);
        }

        // GET: /Comment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentModel commentmodel = _db.Comments.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        public FileResult Download(int? id)
        {
            CommentModel commentModel = _db.Comments.Find(id);

            CommentDownloadViewModel commentToDownload = new CommentDownloadViewModel();
            commentToDownload.ID = commentModel.ID;
            commentToDownload.User = commentModel.User.UserName;
            commentToDownload.Comment = commentModel.Comment;

            string commentAsJson = Newtonsoft.Json.JsonConvert.SerializeObject(commentToDownload);
            byte[] commentAsBytes = System.Text.Encoding.UTF8.GetBytes(commentAsJson);
            return File(commentAsBytes, System.Net.Mime.MediaTypeNames.Text.Plain, String.Format("{0}.{1}", commentModel.ID.ToString(), "json"));
        }

        // POST: /Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CommentModel commentModel = _db.Comments.Find(id);
            _db.Comments.Remove(commentModel);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Unkcon/Controllers/ReplyController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Unkcon.Authentication;
using Unkcon.Models;

namespace Unkcon.Controllers
{
    public class ReplyController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        private UserManagerDecorator _userManager;

        public ReplyController()
        {
            _userManager = new UserManagerDecorator(_db);
        }

        // GET: Reply
        public ActionResult Index(int commentId)
        {
            CommentModel comment = _db.Comments.Find(commentId);
            return View(_db.Replies.ToList().Where(t => t.Comment == comment));
        }

        // GET: Reply/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReplyModels replyModels = _db.Replies.Find(id);
            if (replyModels == null)
            {
                return HttpNotFound();
            }
            return View(replyModels);
        }

        // GET: Reply/Create
        public ActionResult Create(int? commentId)
        {
            if (commentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View();
        }

        // POST: Reply/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Reply")] ReplyModels replyModels, int? commentId)
        {
            if (commentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                CommentModel comment = _db.Comments.Find(commentId);
                replyModels.Comment = comment;

                ApplicationUser currentUser = await _userManager.GetCurrentUserAsync(User.Identity.GetUserId());

                replyModels.User = currentUser;
                _db.Replies.Add(replyModels);
                _db.SaveChanges();
                return RedirectToAction("ViewPotentialMatch", new { commentId = commentId, replyId = replyModels.ID });
            }

            return View(replyModels);
        }

        //NOTE Commented out while I figure out how to handle Edits
        //// GET: Reply/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ReplyModels replyModels = db.Replies.Find(id);
        //    if (replyModels == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(replyModels);
        //}

        //// POST: Reply/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID,Reply")] ReplyModels replyModels)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(replyModels).State = EntityState.Modified;
        //        db.SaveChanges();

        //        return View(replyModels);
        //    }
        //    return View(replyModels);
        //}

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReplyModels replyModels = _db.Replies.Find(id);
            if (replyModels == null)
            {
                return HttpNotFound();
            }
            return View(replyModels);
        }

        // POST: Reply/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ReplyModels replyModels = _db.Replies.Find(id);

            // Get comment ID of reply before deleting it so we can redirect to it.
            int commentId = replyModels.Comment.ID;
            
            _db.Replies.Remove(replyModels);
            _db.SaveChanges();
            return RedirectToAction("Index", new { commentId = commentId });
        }

        public ActionResult ViewPotentialMatch(int? commentId, int? replyId)
        {
            if (commentId == null || replyId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CommentModel commentModel = _db.Comments.Find(commentId);
            if (commentModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ReplyModels replyModel = _db.Replies.Find(replyId);
            if (replyModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PotentialMatchViewModel potentialMatchViewModel = new PotentialMatchViewModel();
            potentialMatchViewModel.Comment = commentModel.Comment;
            potentialMatchViewModel.Reply = replyModel.Reply;

            return View("PotentialMatch", potentialMatchViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Unkcon/Views/Reply/Create.cshtml
@model Unkcon.Models.ReplyModels

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ReplyModels</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Reply, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reply)
                @Html.ValidationMessageFor(model => model.Reply)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Browse", "Comment")
</div>

Unkcon/Views/Reply/Delete.cshtml
@model Unkcon.Models.ReplyModels

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ReplyModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Reply)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reply)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Replies", "Index", "Reply", new { commentId = Model.Comment.ID }, null)
        </div>
    }
</div>

Unkcon/Views/Reply/Details.cshtml
@model Unkcon.Models.ReplyModels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ReplyModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Reply)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reply)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to Replies", "Index", "Reply", new { commentId = Model.Comment.ID }, null)
</p>

Unkcon/Views/Reply/Edit.cshtml
@model Unkcon.Models.ReplyModels

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ReplyModels</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Reply, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reply)
                @Html.ValidationMessageFor(model => model.Reply)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Unkcon/Views/Reply/Index.cshtml
@model IEnumerable<Unkcon.Models.ReplyModels>

@{
    ViewBag.Title = "User Replies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Replies</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Reply)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Reply)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ID, commentID = item.Comment.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to List", "Index", "Comment")
</p>